server:
  port: 80
  servlet:
    context-path: "/course"
  tomcat:
    connection-timeout: -1
spring:
  application:
    name: COURSE
  data:
    mongodb:
      uri: mongodb://localhost:27017/postitdb
  servlet:
    multipart:
      enabled: true
      max-file-size: 2048MB
      max-request-size: 2048MB

videoDirectory:
       path: ${user.home}/VideoPath
logging:
  file:
    name: "${user.home}/${spring.application.name}.log"
  level:
   debug: DEBUG		         
                